/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Automatically buy one of each elf buyable per tick.": "每tick自动购买1个每个精灵可购买。",
    "ego": "自我",
    "Keep elf buyables on row 2 resets.": "将精灵可购买物品保留在第 2 行重置。",
    "Keep elf upgrades on row 2 resets.": "将精灵升级保留在第 2 行重置。",
    "present machines": "礼物机器",
    "presents": "礼物",
    "Reset for +": "重置得到 + ",
    "Elf buyables cost nothing.": "精灵可购买 不花钱。",
    "Gain 100% of elf gain every second.": "每秒获得精灵增益的 100%。",
    "Please check the Discord to see if there are new content\n\t\t\t\tupdates!": "请查看 Discord 是否有新内容\n\t\t\t\t更新！",
    "Unlock the second elf buyable.": "解锁第二个 精灵可购买。",
    "You can buy max present machines.": "您可以购买最大礼物机器。",
    "Amount": "数量",
    "Boosted Morale": "士气高涨",
    "Cost": "成本",
    "Currently": "当前",
    "Effect": "效果",
    "elves": "精灵",
    "I know about it, the game is (unfortunantely) balanced around it not having an effect, and by god I am NOT touching the code ever again.": "我知道这一点，游戏（不幸的是）围绕它进行了平衡，没有任何效果，上帝啊，我再也不会碰代码了。",
    "Make the first elf buyable effect more powerful.": "使第一个精灵可购买效果更加强大。",
    "Multiply elf gain.": "乘以精灵增益。",
    "Multiply present gain based on elves.": "乘以基于精灵的礼物增益。",
    "Multiply present gain.": "乘以礼物增益。",
    "Recruitment Campaign": "招聘会",
    "Start generating presents.": "开始制作礼物。",
    "THIS BUYABLE DOESNT WORK.": "这个可购买不起作用。",
    "Unlock the first elf buyable.": "解锁第一个精灵可购买。",
    "Square root the cost of the first elf buyable.": "第一个精灵可购买的成本的平方根。",
    "Milestone Gotten!": "里程碑获得！",
    "Multiply elf gain based on your presents.": "基于您的礼物乘以精灵增益。",
    "Multiply present gain based on presents.": "基于礼物乘以礼物增益。",
    "trees": "树",
    "Unlock machine challenges.": "解锁机器挑战。",
    "Everybody is at home, so present gain is square rooted.": "每个人都在家，所以现在的收益是平方根的。",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "rona": "萝娜",
    "Finish": "完成",
    "Completed": "已完成",
    "Unlock another Present Machine upgrade.": "解锁另一个礼物机器升级。",
    "Everybody is dying, so elf gain is square rooted.": "每个人都在死去，所以精灵增益是平方根的。",
    "Multiply elf gain based on trees.": "乘以基于树的精灵增益。",
    "Square the present machine effect.": "平方礼物机器效果。",
    "Start collecting leaves.": "开始收集树叶。",
    "Enlist the help of elfs": "寻求精灵的帮助",
    "Mod Your Leafblower": "改装你的吹叶机",
    "Multiply leaf gain based on elfs.": "乘以叶子增益基于精灵。",
    "Multiply leaf gain.": "乘以叶子增益。",
    "This is boring. Give leaves another effect!": "这很无聊。 给叶子另一种效果！",
    "Unlock another tree buyable.": "解锁另1个 树可购买。",
    "I give up. Multiply tree gain by 1e10.": "我放弃。 将树增益乘以 1e10。",
    "Coronavirus": "新冠病毒",
    "Everybody is dying, so elf gain is raised to the power of .001.": "每个人都在死去，所以精灵增益被提高到 0.001 的幂。",
    "It's finally over. We only got set back a few thousand years in history. Things from Trees and Present Machine layers have no effect, and you don't keep elf upgrades upon entering.": "终于结束了。 我们只是在历史上倒退了几千年。 来自 树 和 礼物层 层的东西没有效果，并且您在进入时不会保留精灵升级。",
    "New. Prestige. Layer.": "新的。 声望。 层。",
    "Present Machine effect is cubed.": "当前机器效果是立方的。",
    "Unlock another Present Machine challenge.": "解锁另一个礼物机器挑战。",
    "toys": "玩具",
    "You can buy max toy machines.": "您可以购买最大玩具机器。",
    "You can manually buy only 10 of each toy tier": "您只能手动购买10 个每个玩具层",
    "More Toys": "更多玩具",
    "Morer Toys": "非常多玩具",
    "E: Reset for elves": "E：精灵重置",
    "Dark": "黑暗",
    "Hey, nice! You beat this game. There was originally gonna be 2 more rows, but christmas has come and gone, and TMT is not as easy-to-use as it makes itself out to be. So, for (probably) ever, you reached the end! Good job.": "嘿，不错！ 你赢了这场比赛。 原本会有 2 行，但圣诞节来了又去，TMT 并不像它自己想象的那么好用。 所以，对于（可能）永远，你已经走到了尽头！ 做得好。",
    "M: Reset for present machines": "M：重置当前机器",
    "Morest Toys": "超级多玩具",
    "Shift+T: Reset for toys": "Shift+T：玩具重置",
    "T: Reset for trees": "T：重置树",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "\t\t\t\t": "\t\t\t\t",
    "Multiply present gain by ": "将礼物增益乘以",
    "Raise present gain to the power of ": "提高礼物收益的力量",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \(([\d\.,]+)\)$/,
    /^([\d\.]+)e([\d\.,]+) \(([\d\.,]+)\)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Multiply production of all toy tiers by (.+)$/, '将所有玩具层的产量乘以 $1'],
    [/^multiplying elf gain by (.+)$/, '将精灵增益乘以 $1'],
    [/^Multiply elf gain by (.+)$/, '将精灵增益乘以 $1'],
    [/^(.+) best present machines$/, '$1 最好的礼物机器'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分 $2秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1天 $2小时 $3分 $4秒'],
    [/^You have (.+) manufactured toys, giving a (.+) multiplier to elf gain$/, '你有 $1 个人造玩具，给精灵增益 $2 乘数'],
    [/^Reach (.+) elves to unlock \(You have (.+) elves\)$/, '达到 $1 精灵解锁（你有 $2 精灵）'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) presents$/, '你有 $1 礼物'],
    [/^You have (.+) elves$/, '你有 $1 精灵'],
    [/^You have (.+) leaves$/, '你有 $1 树叶'],
    [/^You have (.+) leaves, multiplying tree gain by (.+)$/, '你有 $1 树叶，乘以树增益 $2'],
    [/^Tier (.+) Toys$/, '$1 层玩具'],
    [/^Producing (.+) Tier (.+) Toys\/s$/, '生产 $1 个 $2层玩具\/秒'],
    [/^Producing (.+) Manufactured Toys\/s$/, '生产 $1 个人造玩具\/秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Next at (.+) presents$/, '下一个在 $1 礼物'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) presents$/, '$1e$2 礼物'],
    [/^([\d\.]+)e([\d\.,]+) trees$/, '$1e$2 树'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^(.+) \/ (.+) elves$/, '$1 \/ $2 精灵'],
    [/^\/([\d\.]+)e([\d\.,]+) Present Machine cost$/, '\/$1e$2 礼物机器成本'],
    [/^\/([\d\.]+)e([\d\.,]+) \(softcapped\) Present Machine cost$/, '\/$1e$2 （软上限）当前机器成本'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^([\d\.]+) best toy machines$/, '$1 最佳玩具机器'],
    [/^([\d\.]+) toys$/, '$1 玩具'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '需要：$1 精灵'],
    [/^Req: (.+) elves$/, '需要：$1 精灵'],
    [/^([\d\.]+)e([\d\.]+) toys$/, '$1e$2 玩具'],
    [/^([\d\.]+)e([\d\.]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.]+) elves$/, '$1e$2 \/ $3e$4 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) presents$/, '$1 礼物'],
    [/^Cost: (\d+) toys$/, '成本：$1 玩具'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Cost: (.+) trees$/, '成本：$1 树'],
    [/^Cost: (.+) elves$/, '成本：$1 精灵'],
    [/^Cost: (.+) present machines$/, '成本：$1 礼物机器'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);